### ISSUE TITLE
Solving with learn test

### ISSUE THREAD

**Issue by winfeigle** [learn-co-curriculum/phase-4-data-structures-queue-from-stack#2]
### Canvas Link

https://learning.flatironschool.com/courses/5295/assignments/180652?module_item_id=398956

### Concern

The `MyQueue#add(value)` spec test won't pass until you've also implemented `#remove` and `#peek` methods... which is fine, but when trying to solve this based on running `learn test` It's kind of misleading. 

### Suggested Changes

Would have been helpful to know that all 3 methods need to be implemented before running `learn test`... Just a thought.

**Comment by lizbur10** [comment]
Hi @winfeigle! Thanks for submitting this suggestion! I agree it can be a little confusing as it is, but I'm hesitant to add that information because I'm afraid it might be a little too big a hint on how to solve the problem. 

Many thanks for contributing to the Flatiron School curriculum 💙
